### ISSUE TITLE
Mocking framework

### ISSUE THREAD

**Issue by oleksiyp** [gruppe11-sms/auditsystem#1]
Hi,

hope find you well with this cold call.

I am an author of [mocking framework for Kotlin](http://mockk.io)

I see you are using mockito-kotlin.

I just want you to be aware that there is solution that fully supports Kotlin and ask to try it in your new/current projects.

I can help you if you answer to this issue.

Thanks and please star [it](https://github.com/oleksiyp/mockk)

**Comment by zlepper** [comment]
Please don't do this kind of thing. If you want to change things, do a pull request. This is nothing but spam as far as I can see.
